// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv"
import { defineConfig } from "prisma/config";
dotenv.config()

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun prisma/seed.ts"
  },
  
  datasource: {
    url: process.env["DATABASE_URL"] || "postgres://dummy:dummy@localhost:5432/dummy",
  },
});
