FROM oven/bun:latest AS base
WORKDIR /app

COPY frontend/package*.json frontend/tsconfig*.json frontend/vite.config.ts frontend/bun.lock frontend/components.json eslint.config.js ./
RUN bun install --frozen-lockfile

RUN frontend/. .

RUN bun run build

FROM nginx:alpine AS prod

COPY --from=base /frontend/dist /usr/share/nginx/html

COPY ./frontend/env.sh /env.sh
RUN chmod +x /env.sh

RUN printf 'server {\n\
  listen 80;\n\
  server_name _;\n\
  root /usr/share/nginx/html;\n\
  index index.html;\n\
\n\
  location / {\n\
    try_files $uri $uri/ /index.html;\n\
  }\n\
\n\
  location = /env-config.js {\n\
    add_header Cache-Control "no-store";\n\
  }\n\
}\n' > /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["/env.sh"]
CMD ["nginx", "-g", "daemon off;"]